# Generated by Django 5.2 on 2025-04-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
    ]
